import Head from 'next/head'
import Contact from '../components/Contact'

import Hero from '../components/Hero'
import Projects from '../components/Projects'



export default function Home() {
  return (
    <>
      <Head>
        <title>SABRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black bg-hero h-full bg-repeat-y'> 
      <Hero></Hero>
      <Projects></Projects>
      <Contact></Contact>
      </main>
    </>
  )
}
